### ISSUE TITLE
Improve Sending Emails to Use  Queues and Mailable class

### ISSUE THREAD

**Issue by KEVINAMAYI** [KEVINAMAYI/savelvue#1]
1. Modify the Mail functions to use Mailable class and also provide an option to enable queues for the mails.
2. Add Email Templates for the verifications emails sent.

**Comment by rono516** [comment]
Please review this [pull request](https://github.com/KEVINAMAYI/savelvue/pull/11) for this issue.

**Comment by KEVINAMAYI** [comment]
No need to add queues by default. So the issue is sorted.
